---
- name: Install MariaDB server packages
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-client
    - MariaDB-server
    - galera

- name: Install Percona tool packages
  yum: name={{ item }} state=present
  with_items:
    - percona-xtrabackup
    - socat

- name: Install MySQL-python
  yum: name=MySQL-python state=present
